public static class CityNames {
    public static readonly Country UK = new Country("London", new string[] {
        "Birmingham",
        "Leeds",
        "Glasgow",
        "Mancheter",
        "Edinburgh",
        "Liverpool",
        "Bristol",
        "Cardiff",
        "Belfast",
        "Newcastle",
        "Sunderland",
        "Brighton",
        "Plymouth",
        "Wolverhampton",
        "Stoke-on-Trent",
        "Derby",
        "Swansea",
        "Southampton",
        "Salford",
        "Portsmouth"
    });
    public static readonly Country Ireland = new Country("Dublin", new string[] {
        "Cork",
        "Limerick",
        "Galway",
        "Waterford",
        "Drogheda",
        "Dundalk",
        "Swords",
        "Bray",
        "Navan",
        "Kilkenny",
        "Ennis",
        "Carlow",
        "Tralee",
        "Newbridge",
        "Portlaoise",
        "Balbriggan",
        "Naas",
        "Athlone",
        "Mullingar",
        "Celbridge"
    });
    public static readonly Country France = new Country("Paris", new string[] {
        "Marseille",
        "Lyon",
        "Toulouse",
        "Nice",
        "Nantes",
        "Strasbourg",
        "Montpellier",
        "Bordeaux",
        "Lille",
        "Rennes",
        "Reims",
        "Saint-Étienne",
        "Toulon",
        "Le Havre",
        "Grenoble",
        "Dijon",
        "Angers",
        "Nîmes",
        "Saint-Denis",
        "Villeurbanne"
    });
    public static readonly Country Germany = new Country("Berlin", new string[] {
        "Hamburg",
        "Munich",
        "Cologne",
        "Frankfurt",
        "Stuttgart",
        "Düsseldorf",
        "Dortmund",
        "Essen",
        "Leipzig",
        "Bremen",
        "Bremen",
        "Dresden",
        "Hanover",
        "Nuremberg",
        "Duisburg",
        "Bochum",
        "Wuppertal",
        "Bielefield",
        "Bonn",
        "Münster"
    });
    public static readonly Country Spain = new Country("Madrid", new string[] {
        "Barcelona",
        "Valencia",
        "Serville",
        "Zaragoza",
        "Málaga",
        "Murcia",
        "Palma",
        "Las Palmas",
        "Bilbao",
        "Alicante",
        "Córdoba",
        "Valladolid",
        "Vigo",
        "Gijón",
        "L'Hospitalet",
        "Vitoria-Gasteiz",
        "A Coruña",
        "Elche",
        "Granada",
        "Terrassa"
    });
    public static readonly Country Italy = new Country("Rome", new string[] {
        "Milan",
        "Naples",
        "Turin",
        "Palermo",
        "Genoa",
        "Bologna",
        "Florence",
        "Bari",
        "Catania",
        "Verona",
        "Venice",
        "Messina",
        "Padua",
        "Trieste",
        "Brescia",
        "Parma",
        "Taranto",
        "Prato",
        "Modena",
        "Reggio Calabria"
    });
    public static readonly Country Poland = new Country("Warsaw", new string[] {
        "Kraków",
        "Łódź",
        "Wrocław",
        "Poznań",
        "Gdańsk",
        "Szczecin",
        "Bydgoszcz",
        "Lublin",
        "Białystok",
        "Katowice",
        "Gdynia",
        "Częstochowa",
        "Radom",
        "Toruń",
        "Sosnowiec",
        "Rzeszów",
        "Kielce",
        "Gliwice",
        "Olsztyn",
        "Zabrze"
    });
    public static readonly Country Russia = new Country("Moscow", new string[] {
        "Saint Petersburg",
        "Novosibirsk",
        "Yekaterinburg",
        "Kazan",
        "Nizhny Novogorod",
        "Chelyabinsk",
        "Samara",
        "Omsk",
        "Rostov-on-Don",
        "Ufa",
        "Krasnoyarsk",
        "Voronezh",
        "Perm",
        "Volgograd",
        "Krasnodar",
        "Saratov",
        "Tyumen",
        "Tolyatti",
        "Izhevsk",
        "Barnaul"
    });
    public static readonly Country TheNetherlands = new Country("Amsterdam", new string[] {
        "Utrecht",
        "The Hague",
        "Rotterdam",
        "Alkmaar",
        "Haarlem",
        "Eindhoven",
        "Groningen",
        "Almere",
        "Breda",
        "Enschede",
        "Arnhem",
        "Den Bosch",
        "Zaanstad",
        "Nijmegen",
        "Amersfoort",
        "Zwolle",
        "Maastricht",
        "Leiden",
        "Tilburg",
        "Apeldoorn"
    });
    public static readonly Country Turkey = new Country("Istanbul", new string[] {
        "Ankara",
        "İzmir",
        "Bursa",
        "Adana",
        "Gaziantep",
        "Konya",
        "Antalya",
        "Kayseri",
        "Mersin",
        "Eskişehir",
        "Diyarbakır",
        "Samsun",
        "Denizli",
        "Şanlıurfa",
        "Adapazarı",
        "Malatya",
        "Kahramanmaraş",
        "Erzurum",
        "Van",
        "Batman"
    });
    public static readonly Country Hungary = new Country("Budapest", new string[] {
        "Debrecen",
        "Szeged",
        "Miskolc",
        "Pécs",
        "Győr",
        "Nyíregyháza",
        "Kecskemét",
        "Székesfehérvár",
        "Szombathely",
        "Szolnok",
        "Érd",
        "Tatabánya",
        "Sopron",
        "Kaposvár",
        "Veszprém",
        "Békéscsaba",
        "Zalaegerszeg",
        "Eger",
        "Nagykanizsa",
        "Dunakeszi"
    });
    public static readonly Country Iran = new Country("Tehran", new string[] {
        "Mashhad",
        "Isfahan",
        "Karaj",
        "Shiraz",
        "Tabriz",
        "Qom",
        "Ahvaz",
        "Kermanshah",
        "Urmia",
        "Rasht",
        "Zahedan",
        "Hamadan",
        "Kerman",
        "Yazd",
        "Ardabil",
        "Bandar Abbas",
        "Arak",
        "Eslamshahr",
        "Zanjan",
        "Sanandaj"
    });
    public static readonly Country Sweden = new Country("Stockholm", new string[] {
        "Göteborg",
        "Malmö",
        "Uppsala",
        "Västerås",
        "Örebro",
        "Linköping",
        "Helsingborg",
        "Eskilstuna",
        "Jönköping",
        "Norrköping",
        "Lund",
        "Umeå",
        "Gävle",
        "Borås",
        "Södertälje",
        "Halmstad",
        "Växjö",
        "Karlstad",
        "Sundsvall",
        "Östersund"
    });

    public static readonly Country[] countries = {UK, Ireland, France, Germany, Spain, Italy, Poland, Russia, TheNetherlands, Turkey, Hungary, Iran, Sweden};
}

public struct Country {
    public string capitalCity;
    public string[] names;

    public Country(string capitalCity, string[] names) {
        this.capitalCity = capitalCity;
        this.names = names;
    }
}