public static class CityNames {
    public static readonly Country GB = new Country("UK", "London", new string[] {
        "Birmingham",
        "Leeds",
        "Glasgow",
        "Manchester",
        "Edinburgh",
        "Liverpool",
        "Bristol",
        "Cardiff",
        "Belfast",
        "Newcastle",
        "Sunderland",
        "Brighton",
        "Plymouth",
        "Wolverhampton",
        "Stoke-on-Trent",
        "Derby",
        "Swansea",
        "Southampton",
        "Salford",
        "Portsmouth"
    });
    public static readonly Country IE = new Country("Ireland", "Dublin", new string[] {
        "Cork",
        "Limerick",
        "Galway",
        "Waterford",
        "Drogheda",
        "Dundalk",
        "Swords",
        "Bray",
        "Navan",
        "Kilkenny",
        "Ennis",
        "Carlow",
        "Tralee",
        "Newbridge",
        "Portlaoise",
        "Balbriggan",
        "Naas",
        "Athlone",
        "Mullingar",
        "Celbridge"
    });
    public static readonly Country FR = new Country("France", "Paris", new string[] {
        "Marseille",
        "Lyon",
        "Toulouse",
        "Nice",
        "Nantes",
        "Strasbourg",
        "Montpellier",
        "Bordeaux",
        "Lille",
        "Rennes",
        "Reims",
        "Saint-Étienne",
        "Toulon",
        "Le Havre",
        "Grenoble",
        "Dijon",
        "Angers",
        "Nîmes",
        "Saint-Denis",
        "Villeurbanne"
    });
    public static readonly Country DE = new Country("Germany", "Berlin", new string[] {
        "Hamburg",
        "Munich",
        "Cologne",
        "Frankfurt",
        "Stuttgart",
        "Düsseldorf",
        "Dortmund",
        "Essen",
        "Leipzig",
        "Bremen",
        "Bremen",
        "Dresden",
        "Hanover",
        "Nuremberg",
        "Duisburg",
        "Bochum",
        "Wuppertal",
        "Bielefield",
        "Bonn",
        "Münster"
    });
    public static readonly Country ES = new Country("Spain", "Madrid", new string[] {
        "Barcelona",
        "Valencia",
        "Serville",
        "Zaragoza",
        "Málaga",
        "Murcia",
        "Palma",
        "Las Palmas",
        "Bilbao",
        "Alicante",
        "Córdoba",
        "Valladolid",
        "Vigo",
        "Gijón",
        "L'Hospitalet",
        "Vitoria-Gasteiz",
        "A Coruña",
        "Elche",
        "Granada",
        "Terrassa"
    });
    public static readonly Country IT = new Country("Italy", "Rome", new string[] {
        "Milan",
        "Naples",
        "Turin",
        "Palermo",
        "Genoa",
        "Bologna",
        "Florence",
        "Bari",
        "Catania",
        "Verona",
        "Venice",
        "Messina",
        "Padua",
        "Trieste",
        "Brescia",
        "Parma",
        "Taranto",
        "Prato",
        "Modena",
        "Reggio Calabria"
    });
    public static readonly Country PL = new Country("Poland", "Warsaw", new string[] {
        "Kraków",
        "Łódź",
        "Wrocław",
        "Poznań",
        "Gdańsk",
        "Szczecin",
        "Bydgoszcz",
        "Lublin",
        "Białystok",
        "Katowice",
        "Gdynia",
        "Częstochowa",
        "Radom",
        "Toruń",
        "Sosnowiec",
        "Rzeszów",
        "Kielce",
        "Gliwice",
        "Olsztyn",
        "Zabrze"
    });
    public static readonly Country RU = new Country("Russia", "Moscow", new string[] {
        "Saint Petersburg",
        "Novosibirsk",
        "Yekaterinburg",
        "Kazan",
        "Nizhny Novogorod",
        "Chelyabinsk",
        "Samara",
        "Omsk",
        "Rostov-on-Don",
        "Ufa",
        "Krasnoyarsk",
        "Voronezh",
        "Perm",
        "Volgograd",
        "Krasnodar",
        "Saratov",
        "Tyumen",
        "Tolyatti",
        "Izhevsk",
        "Barnaul"
    });
    public static readonly Country NL = new Country("The Netherlands", "Amsterdam", new string[] {
        "Utrecht",
        "The Hague",
        "Rotterdam",
        "Alkmaar",
        "Haarlem",
        "Eindhoven",
        "Groningen",
        "Almere",
        "Breda",
        "Enschede",
        "Arnhem",
        "Den Bosch",
        "Zaanstad",
        "Nijmegen",
        "Amersfoort",
        "Zwolle",
        "Maastricht",
        "Leiden",
        "Tilburg",
        "Apeldoorn"
    });
    public static readonly Country TR = new Country("Turkey", "Istanbul", new string[] {
        "Ankara",
        "İzmir",
        "Bursa",
        "Adana",
        "Gaziantep",
        "Konya",
        "Antalya",
        "Kayseri",
        "Mersin",
        "Eskişehir",
        "Diyarbakır",
        "Samsun",
        "Denizli",
        "Şanlıurfa",
        "Adapazarı",
        "Malatya",
        "Kahramanmaraş",
        "Erzurum",
        "Van",
        "Batman"
    });
    public static readonly Country HU = new Country("Hungary", "Budapest", new string[] {
        "Debrecen",
        "Szeged",
        "Miskolc",
        "Pécs",
        "Győr",
        "Nyíregyháza",
        "Kecskemét",
        "Székesfehérvár",
        "Szombathely",
        "Szolnok",
        "Érd",
        "Tatabánya",
        "Sopron",
        "Kaposvár",
        "Veszprém",
        "Békéscsaba",
        "Zalaegerszeg",
        "Eger",
        "Nagykanizsa",
        "Dunakeszi"
    });
    public static readonly Country IR = new Country("Iran", "Tehran", new string[] {
        "Mashhad",
        "Isfahan",
        "Karaj",
        "Shiraz",
        "Tabriz",
        "Qom",
        "Ahvaz",
        "Kermanshah",
        "Urmia",
        "Rasht",
        "Zahedan",
        "Hamadan",
        "Kerman",
        "Yazd",
        "Ardabil",
        "Bandar Abbas",
        "Arak",
        "Eslamshahr",
        "Zanjan",
        "Sanandaj"
    });
    public static readonly Country SE = new Country("Sweden", "Stockholm", new string[] {
        "Göteborg",
        "Malmö",
        "Uppsala",
        "Västerås",
        "Örebro",
        "Linköping",
        "Helsingborg",
        "Eskilstuna",
        "Jönköping",
        "Norrköping",
        "Lund",
        "Umeå",
        "Gävle",
        "Borås",
        "Södertälje",
        "Halmstad",
        "Växjö",
        "Karlstad",
        "Sundsvall",
        "Östersund"
    });
    public static readonly Country CN = new Country("China", "Beijing", new string[] {
        "Shanghai",
        "Chongqing",
        "Tinajin",
        "Guangzhou",
        "Shenzhen",
        "Chengdu",
        "Nanjing",
        "Wuhan",
        "Xi'an",
        "Hangzhou",
        "Dongguan",
        "Foshan",
        "Shenyang",
        "Harbin",
        "Qingdao",
        "Dalian",
        "Jinan",
        "Zhengzhou",
        "Changsha",
        "Kunming"
    });
    public static readonly Country JP = new Country("Japan", "Tokyo", new string[] {
        "Yokohama",
        "Osaka",
        "Nagoya",
        "Sapporo",
        "Fukuoka",
        "Kawasaki",
        "Kobe",
        "Kyoto",
        "Saitama",
        "Hiroshima",
        "Sendai",
        "Chiba",
        "Kitakyushu",
        "Setagaya",
        "Sakai",
        "Niigata",
        "Nerima",
        "Kumamoto",
        "Sagamihara",
        "Okayama",
    });
    public static readonly Country KR = new Country("South Korea", "Seoul", new string[] {
        "Busan",
        "Incheon",
        "Daegu",
        "Daejeon",
        "Gwangju",
        "Suwon",
        "Ulsan",
        "Yongin",
        "Goyang",
        "Changwon",
        "Seongnam",
        "Hwaseong",
        "Cheongju",
        "Bucheon",
        "Ansan",
        "Namyangju",
        "Cheonan",
        "Jeonju",
        "Gimhae",
        "Pyeongtaek"
    });
    public static readonly Country VN = new Country("Vietnam", "Hanoi", new string[] {
        "Ho Chi Minh",
        "Haiphong",
        "Cantho",
        "Danang",
        "Biên Hòa",
        "Thuận An",
        "Dĩ An",
        "Nha Trang",
        "Thanh Hóa",
        "Huế",
        "Vinh",
        "Buôn Ma Thuột",
        "Thái Nguyên",
        "Vũng Tàu",
        "Hải Dương",
        "Quy Nhơn",
        "Long Xuyên",
        "Thái Bình",
        "Quảng Ngãi",
        "Rạch Giá"
    });
    public static readonly Country KE = new Country("Kenya", "Nairobi", new string[] {
        "Mombasa",
        "Kisumu",
        "Nakuru",
        "Ruiru",
        "Eldoret",
        "Kikuyu",
        "Kisii",
        "Thika",
        "Meru",
        "Kangundo-Tala",
        "Malindi",
        "Naivasha",
        "Kitui",
        "Machakos",
        "Mlolongo",
        "Mavoko",
        "Karuri",
        "Nyeri",
        "Kilifi",
        "Garissa",
        "Vihiga"
    });
    public static readonly Country ET = new Country("Ethiopia", "Addis Ababa", new string[] {
        "Dessie",
        "Mekelle",
        "Adama",
        "Awassa",
        "Gondar",
        "Bahir Dar",
        "Dire Dawa",
        "Sodo",
        "Kombolcha",
        "Jimma",
        "Jijiga",
        "Debre Birhan",
        "Shashamane",
        "Bishoftu",
        "Debre Mark'os",
        "Arba Minch",
        "Hosaena",
        "Harar",
        "Dilla",
        "Nekemte"
    });
    public static readonly Country Overflow = new Country("Overflow", "Overflow", new string[] {
        "Overflow"
    });

    public static readonly Country[] countries = {
        GB,
        IE,
        FR,
        DE,
        ES,
        IT,
        PL,
        RU,
        NL,
        TR,
        HU,
        IR,
        SE,
        CN,
        JP,
        KR,
        VN,
        KE,
        ET
    };
}

public struct Country {
    public string countryName;
    public string capitalCity;
    public string[] names;

    public Country(string countryName, string capitalCity, string[] names) {
        this.countryName = countryName;
        this.capitalCity = capitalCity;
        this.names = names;
    }
}